name: Run System Tests

on:
  push:
    branches: [ "main", "final-version", "Configure-CI" ]
  pull_request:
    branches: [ "main", "final-version", "Configure-CI" ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      BROWSER_WIDTH: ${{ secrets.BROWSER_WIDTH }}
      HEADLESS: ${{ secrets.HEADLESS }}
      BROWSER_HEIGHT: ${{ secrets.BROWSER_HEIGHT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Prepare Logs Directory
      run: |
        mkdir -p ./logs
        sudo chown -R 1000:1000 ./logs

    - name: Run TeamCity Server Container
      run: |
        docker run -d --name teamcity-server-instance -v ${{ github.workspace }}/logs:/opt/teamcity/logs -p 8111:8111 jetbrains/teamcity-server
        echo "Waiting for TeamCity server to start..."
        for i in {1..30}; do
          if docker logs teamcity-server-instance 2>&1 | grep -q 'TeamCity process PID is'; then
            echo "TeamCity server started successfully."
            break
          fi
          echo "Waiting..."
          sleep 5
        done
        echo "Docker Status:"
        docker ps -a
        echo "TeamCity Server Logs:"
        docker logs teamcity-server-instance

    - name: Check Port Availability
      run: |
        echo "Checking if port 8111 is open..."
        if nc -z localhost 8111; then
          echo "Port 8111 is open."
        else
          echo "Port 8111 is not open."
        fi

    - name: Retrieve Super User Token
      run: |
        if docker exec teamcity-server-instance cat /data/teamcity/logs/teamcity-server.log 2>&1 | grep 'Super user authentication token' > superuser_token.txt; then
          token=$(cat superuser_token.txt | grep -oP 'Super user authentication token: \K[0-9]+')
          echo "Super user token: $token"
          echo "SUPER_USER_TOKEN=$token" >> $GITHUB_ENV
        else
          echo "Failed to retrieve super user token. Printing log for diagnosis:"
          docker logs teamcity-server-instance
        fi

    - name: Run TeamCity Agent Container
      run: |
        docker run -d --name teamcity-agent-instance -e SERVER_URL="http://localhost:8111" jetbrains/teamcity-agent

    - name: Install Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.10 python3-pip
        pip install -r requirements.txt

    - name: Run Set Up Test
      run: |
        playwright install
        pytest -v test/frontend/test_set_up.py --alluredir=results

    - name: Run Tests
      run: |
        pytest -v --alluredir=results --ignore=test/frontend/test_set_up.py
