
name: CI

on:
  push:
    branches: [ "main", "final-version", "Configure-CI" ]
  pull_request:
    branches: [ "main", "final-version", "Configure-CI" ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Verify services
      run: |
            ls -la /tmp/build/volume/teamcity-server-logs/
            ls -la ${{ github.workspace }}
    - name: Install Python Dependencies
      run: |
            sudo apt-get update
            sudo apt-get install -y python3.10 python3-pip
            pip install -r requirements.txt

    - name: Run Set Up Test
      run: |
            playwright install
            pytest -v test/frontend/test_set_up.py

    - name: Run Tests
      run: |
            pytest -v --ignore=test/frontend/test_set_up.py


    services:
      teamcity-server-instance:
        image: jetbrains/teamcity-server
        ports:
          - 8111:8111
        volumes:
          - /tmp/build/volume/teamcity-server-logs:/opt/teamcity/logs
          - /tmp/build/volume/teamcity-server-data:/data/teamcity_server/datadir
        options: >-
          --name teamcity-server
      teamcity-agent-instance:
        image: jetbrains/teamcity-agent
        env:
          SERVER_URL: http://teamcity-server:8111
        options: >-
          --name teamcity-agent