name: Run System Tests

on:
  push:
    branches: [ "main", "final-version", "Configure-CI" ]
  pull_request:
    branches: [ "main", "final-version", "Configure-CI" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    needs: setup-env

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.10 python3-pip
        pip install -r requirements.txt

    - name: Run Set Up Test
      run: |
        playwright install
        pytest -v test/frontend/test_set_up.py

    - name: Run Tests
      run: |
        pytest -v --ignore=test/frontend/test_set_up.py
