name: Run System Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Run Tests
      run: |
        docker build -t my-test-env -f Dockerfile .
        docker run my-test-env /bin/bash -c "cd /path/to/tests && ./test_script.sh"