name: Run System Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Run TeamCity Server Container
      run: |
        docker run -d --name teamcity-server-instance -v ${{ github.workspace }}/logs:/opt/teamcity/logs -p 8111:8111 jetbrains/teamcity-server
        echo "Waiting for TeamCity server to start..."
        for i in {1..60}; do
          if docker logs teamcity-server-instance 2>&1 | grep -q 'TeamCity process PID is'; then
            echo "TeamCity server started successfully."
            break
          fi
          echo "Waiting..."
          sleep 10
        done

    - name: Retrieve Super User Token
      run: |
        docker exec teamcity-server-instance cat /data/teamcity/logs/teamcity-server.log | grep 'Super user authentication token' > superuser_token.txt
        token=$(cat superuser_token.txt | grep -oP 'Super user authentication token: \K[0-9]+')
        echo "Super user token: $token"
        echo "SUPER_USER_TOKEN=$token" >> $GITHUB_ENV

    - name: Run TeamCity Agent Container
      run: |
        docker run -d --name teamcity-agent-instance -e SERVER_URL="http://localhost:8111" jetbrains/teamcity-agent

    - name: Install Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.10 python3-pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        playwright install
        pytest -v --alluredir=results

    - name: Start Allure Report
      run: |
        docker run -d -p 5050:5050 -v ${{ github.workspace }}/results:/allure-report frankescobar/allure-docker-service
        sleep 10

    - name: Display Allure Report URL
      run: |
        echo "Allure Report is available at http://localhost:5050"
